[package]
name = "gsheet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
google-sheets4 = "6.0.0"
tokio = { version = "1.48.0", features = ["full"] }
serde_json = "1.0.148"
thiserror = "2.0.17"
# yup-oauth2 = "12.1.1"
